"""Chaldean compound numbers with their numerological meanings."""

GOOD_COMPOUNDS = {
    1:  "Independent leadership and pioneering spirit",
    3:  "Creative expression and social charm",
    5:  "Freedom, adaptability and dynamic energy",
    6:  "Harmony, love and domestic balance",
    9:  "Universal compassion and humanitarian strength",
    14: "Movement, communication and fortunate change",
    15: "Magnetic charm and material prosperity",
    19: "Rising Sun — success, honour and self-reliance",
    23: "Royal Star of the Lion — protection and success",
    24: "Love, support and artistic talent",
    27: "Sceptre — authority, command and reward",
    32: "Communication, influence and unexpected luck",
    33: "Luxury, prosperity and creative mastery",
    37: "Harmony in partnerships and personal magnetism",
    41: "Recognition, victory and lasting achievement",
    42: "Stable wealth, support and long-term success",
    46: "Worldly power and high ambition",
    51: "Warrior spirit — courage and ultimate triumph",
    55: "Exceptional intellect and freedom of thought",
    59: "Spiritual wisdom and inner strength",
    64: "Stability through effort and perseverance",
    69: "Compassion, family devotion and healing",
}

NEUTRAL_COMPOUNDS = {
    2:  "Cooperation and diplomacy",
    4:  "Discipline and hard work",
    7:  "Introspection and spiritual seeking",
    8:  "Ambition and material focus",
    10: "Completion and new beginnings",
    11: "Intuition and spiritual insight",
    12: "Sacrifice and learning through experience",
    16: "Unexpected change and spiritual awakening",
    17: "Immortality — spiritual strength after struggle",
    18: "Conflict between material and spiritual",
    20: "Awakening — sensitivity and patience required",
    21: "Crown of the Magi — advancement and honours",
    22: "Submission — caution around others' plans",
    25: "Strength through experience and observation",
    26: "Partnerships that may bring difficulties",
    28: "Promise of success undermined by trust issues",
    29: "Uncertainties and trials of strength",
    30: "Thoughtful detachment and mental focus",
    31: "Solitude and self-reliance",
    34: "Spiritual strength but material struggle",
    35: "Business success with personal compromise",
    36: "Philosophical wisdom and creative power",
    38: "Partnerships with mixed material outcomes",
    39: "Creative imagination with scattered energy",
    40: "Focused discipline with limited flexibility",
    43: "Revolution — upheaval before progress",
    44: "Ambition and discipline at a high cost",
    45: "Wisdom gained through experience",
    47: "Reflection and inner development",
    48: "Planning and long-term strategy",
    49: "Completion of a cycle",
    50: "Infinite potential with need for grounding",
}
